[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Or your preferred Node version

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
