[build]
  command = "cd frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/dist"
  node_version = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
