[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--production=false"

[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  node_version = "20.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
